In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('Data/preprocessed_dataset.csv')

df.head()

,year,life_ladder_year_median,country,region,subregion,least_developed_countries,session,speech,life_ladder,log_gdp_per_capita,...,imports,exports,fear,anger,surprise,sadness,disgust,joy,anticipation,happiness_classification
0,2005,6.600104,Mexico,Americas,Latin America and the Caribbean,no,60,past year we member states embarked upon refor...,6.580658,9.791636,...,244001.477949,214232.956653,0.044010,0.029340,0.034230,0.031785,0.026895,0.056235,0.100244,not-happy
1,2005,6.600104,Japan,Asia,Eastern Asia,no,60,like first foremost convey again sincere sympa...,6.515817,10.551915,...,515219.234003,594895.500416,0.060606,0.028520,0.033868,0.035651,0.024955,0.057041,0.112299,not-happy
2,2005,6.600104,Belgium,Europe,Western Europe,no,60,allow congratulate warmly sir election preside...,7.262290,10.743808,...,318590.363059,334279.746500,0.072381,0.049524,0.040000,0.038095,0.034286,0.097143,0.091429,happy
3,2005,6.600104,Pakistan,Asia,Southern Asia,no,60,let congratulate president current session for...,5.224658,8.252209,...,25410.566139,16049.902535,0.059840,0.043883,0.019947,0.041223,0.031915,0.070479,0.093085,not-happy
4,2005,6.600104,France,Europe,Western Europe,no,60,speaking first time rostrum wish reaffirm impo...,7.093393,10.636769,...,503796.442300,462876.748800,0.070225,0.043539,0.036517,0.036517,0.028090,0.081461,0.102528,happy

In [6]:
df['gdp_per_capita'] = np.exp(df['log_gdp_per_capita'])

In [7]:
df['gdp_per_capita'].head()

0    17883.531015
1    38250.624609
2    46342.177785
3     3836.089279
4    41638.033473
Name: gdp_per_capita, dtype: float64

Note that `gdp_per_capita` was given in US dollars and `imports` and `exports` in millions of US dollars.

In [8]:
df['norm_imports'] = df['imports'] / df['gdp_per_capita']
df['norm_exports'] = df['exports'] / df['gdp_per_capita']

In [9]:
filtered_df = df.loc[:,['happiness_classification', 'norm_imports', 'norm_exports', \
                 'fear', 'anger', 'surprise', 'sadness', 'disgust', 'joy', 'anticipation']]

filtered_df.head()

,happiness_classification,norm_imports,norm_exports,fear,anger,surprise,sadness,disgust,joy,anticipation
0,not-happy,13.643921,11.979343,0.044010,0.029340,0.034230,0.031785,0.026895,0.056235,0.100244
1,not-happy,13.469564,15.552570,0.060606,0.028520,0.033868,0.035651,0.024955,0.057041,0.112299
2,happy,6.874739,7.213294,0.072381,0.049524,0.040000,0.038095,0.034286,0.097143,0.091429
3,not-happy,6.624081,4.183923,0.059840,0.043883,0.019947,0.041223,0.031915,0.070479,0.093085
4,happy,12.099429,11.116681,0.070225,0.043539,0.036517,0.036517,0.028090,0.081461,0.102528

In [10]:
print(filtered_df.shape)

(932, 10)

In [11]:
filtered_df = filtered_df.dropna()

print(filtered_df.shape)

(921, 10)

In [12]:
filtered_df.to_csv('Data/final_dataset.csv', index=False)